/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include <stdint.h>

#define RCC_CR      0x40023800UL
#define RCC_CFGR    (RCC_CR + 0x08)

int main(void)
{
    volatile uint32_t *prccCR   = (uint32_t*)RCC_CR;
    volatile uint32_t *prccCFGR = (uint32_t*)RCC_CFGR;

    // Enable HSE (bit 16)
    *prccCR |= (1 << 16);

    // Wait until HSE is ready (bit 17)
    while(!(*prccCR & (1 << 17)));

    // Select HSE as system clock (SW bits = 01)
    *prccCFGR &= ~(3 << 0);   // Clear SW bits
    *prccCFGR |=  (1 << 0);   // Set SW = 01 (HSE)

    // Wait until HSE becomes system clock (SWS bits = 01)
    while(((*prccCFGR >> 2) & 0x3) != 0x01);
    *prccCFGR |=1<<22;

    // Infinite loop
    for(;;);
}
